name: Deploy to Prod

on:
  release:
    types: [published]

jobs:
  push_to_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Check if this is the latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_RELEASE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest)
          LATEST_TAG=$(echo $LATEST_RELEASE | jq -r .tag_name)
          CURRENT_TAG=${{ github.event.release.tag_name }}
          
          if [[ "$LATEST_TAG" != "$CURRENT_TAG" ]]; then
            echo "This release is not the latest. Exiting..."
            echo "::set-output name=continue::false"
            exit 0
          else
            echo "::set-output name=continue::true"
          fi

      - name: Test Echo
        if: steps.check_latest.outputs.continue == 'true'
        run: |
          echo "Hello World!"